
# Makers Mate GPT configuration (human- and machine-friendly)
# ------------------------------------------------------------------
# NOTE on capabilities:
# In OpenAI Custom GPTs, these flags are ADVISORY ONLY for humans.
# They do not enforce technical restrictions (e.g., domain whitelists).
# If you later self-host or add a retrieval/browsing layer, scripts can
# parse this YAML and enforce the rules below.


name: "Makers Mate"
description: "Lowell Makes community helper — answers from shop rules, bylaws, and docs."
owner_org: "Lowell Makes"
visibility: "public"
capabilities:
  
web_browsing: false  # Advisory in ChatGPT. If you enable browsing in the Builder UI,
                     # the GPT can access the wider web (no domain fencing). Enforceable
                     # domain limits are only possible in self-hosted/retriever setups.
code_interpreter: false
image_generation: false

style:
  persona: "friendly, concise, accurate"
  format_preferences:
    - "short answer first"
    - "steps/checklist if helpful"
    - "cite file names/sections when used"
knowledge:
  paths:
    - "../knowledge"
allowed_domains:
  - "lowellmakes.com"
  - "wiki.lowellmakes.com"
governance:
  escalation: ["Executive Committee", "Shop Captains Council"]
versioning:
  scheme: "calver-minor"
